<?php
/** @var Magento\Framework\View\Element\Template $block*/
/** @var Irm\Blog\ViewModel\Post $postVm */

$postVm = $block->getData('post_vm');
?>
<div class="blog-post-list">
    <h1><?= __('Blog post') ?></h1>
    <ul>
    <?php foreach ($postVm->getList() as $posts): ?>
        <li>
            <a href="<?= $block->getUrl('blog/post/detail',['id' => $posts->getData('id')]) ?>">
                <?php $posts->getData('title') ?>
            </a>
        </li>
        <?php endforeach ?>
    </ul>
    <p><?= __('Post count: %1',3)?></p>
</div>
